import React from 'react';
import {
  X,
  User,
  Award,
  Mic,
  MicOff,
  ChevronRight,
  Plus,
  Trash2,
  Edit2,
  Check,
  Search,
  CalendarDays,
  Clock,
  FileText,
  AlertTriangle,
  Building2,
  RefreshCw,
  CheckCircle2,
  XCircle,
  Wallet,
  Ban,
  MapPin,
  Truck,
  Package,
  ShieldCheck,
  Info
} from 'lucide-react';

// Standardized Icon wrapper for consistent styling
const iconClass = "w-5 h-5";

export const Icon = {
  X: ({ className = iconClass, ...props }: any) => <X className={className} {...props} />,
  User: ({ className = iconClass, ...props }: any) => <User className={className} {...props} />,
  Award: ({ className = iconClass, ...props }: any) => <Award className={className} {...props} />,
  Mic: ({ className = iconClass, ...props }: any) => <Mic className={className} {...props} />,
  MicOff: ({ className = iconClass, ...props }: any) => <MicOff className={className} {...props} />,
  ChevronRight: ({ className = iconClass, ...props }: any) => <ChevronRight className={className} {...props} />,
  Plus: ({ className = iconClass, ...props }: any) => <Plus className={className} {...props} />,
  Trash2: ({ className = iconClass, ...props }: any) => <Trash2 className={className} {...props} />,
  Edit2: ({ className = iconClass, ...props }: any) => <Edit2 className={className} {...props} />,
  Check: ({ className = iconClass, ...props }: any) => <Check className={className} {...props} />,
  Search: ({ className = iconClass, ...props }: any) => <Search className={className} {...props} />,
  CalendarDays: ({ className = iconClass, ...props }: any) => <CalendarDays className={className} {...props} />,
  Clock: ({ className = iconClass, ...props }: any) => <Clock className={className} {...props} />,
  FileText: ({ className = iconClass, ...props }: any) => <FileText className={className} {...props} />,
  AlertTriangle: ({ className = iconClass, ...props }: any) => <AlertTriangle className={className} {...props} />,
  Building2: ({ className = iconClass, ...props }: any) => <Building2 className={className} {...props} />,
  RefreshCw: ({ className = iconClass, ...props }: any) => <RefreshCw className={className} {...props} />,
  CheckCircle2: ({ className = iconClass, ...props }: any) => <CheckCircle2 className={className} {...props} />,
  XCircle: ({ className = iconClass, ...props }: any) => <XCircle className={className} {...props} />,
  Wallet: ({ className = iconClass, ...props }: any) => <Wallet className={className} {...props} />,
  Ban: ({ className = iconClass, ...props }: any) => <Ban className={className} {...props} />,
  MapPin: ({ className = iconClass, ...props }: any) => <MapPin className={className} {...props} />,
  Truck: ({ className = iconClass, ...props }: any) => <Truck className={className} {...props} />,
  Package: ({ className = iconClass, ...props }: any) => <Package className={className} {...props} />,
  ShieldCheck: ({ className = iconClass, ...props }: any) => <ShieldCheck className={className} {...props} />,
  Info: ({ className = iconClass, ...props }: any) => <Info className={className} {...props} />,
};
